# Generated by cucumber-sinatra. (2014-01-16 15:51:06 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'sack.rb')

require 'capybara'
require 'capybara-webkit'
require 'capybara/dsl'
require 'capybara/cucumber'
require 'rspec'
require 'simplecov'

SimpleCov.start

Capybara.app = Sack
Capybara.default_driver = :webkit
Capybara.javascript_driver = :webkit
Capybara.default_wait_time = 5

class SackWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Sack.new
end
