# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require File.join(File.dirname(__FILE__), '..', 'sack')
 
require 'sinatra'
require 'rspec'
require 'rack/test'
require 'capybara'
require 'capybara/rspec'
require 'capybara-webkit'
require 'mongoid'
require 'mongoid-rspec'
require 'simplecov'

include Rack::Test::Methods

SimpleCov.start

Capybara.app = Sack 

Capybara.default_driver = :webkit
 
#specify that the app is a Sinatra app
def app
   Sinatra::Application
end

set :environment, :test

RSpec.configure do |config|
  
  config.before(:each) do
    Mongoid.purge!
  end

  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
  config.include Capybara::DSL
  config.include Mongoid::Matchers
end
